#!/bin/sh
# nvidia-grub-setup - blacklist nouveau/nova, enable nvidia, update GRUB.
# Part of the spk 'nvidia' (595 series) and 'nvidia-legacy' (580 series) packages.
# Idempotent: safe to run multiple times. Must be run as root for a live
# system. It is also executed automatically by `spk get` via the package's
# usr/lib/spk/postinstall hook (with SPK_ROOT pointing at the install target).
#
# Env:
#   SPK_ROOT   install target prefix ("/" or empty = live system).
#              Honored so `spk get <pkg> --root DIR` configures DIR, not /.
#
# What it does (under $ROOT):
#   0) Overlays the payload's usr/ and etc/ into the system (libs, kernel
#      modules, firmware, Xorg/udev data) and records them for `spk rm`
#   1) Writes etc/modprobe.d/nvidia.conf (blacklist nouveau/nova + nvidia opts)
#   2) Ensures etc/default/grub GRUB_CMDLINE_LINUX_DEFAULT contains:
#        nvidia-drm.modeset=1 nvidia-drm.fbdev=1 modprobe.blacklist=nouveau,nova_core,nova_drm
#   3) Runs depmod for the shipped 7.2.0 modules (and the running kernel)
#   4) Regenerates boot/grub/grub.cfg via grub-mkconfig (live system only)
#   5) Tries to rebuild the initramfs so the blacklist takes effect early
#      (live system only; for --root targets it prints what to run instead)
set -eu

WANT_PARAMS="nvidia-drm.modeset=1 nvidia-drm.fbdev=1 modprobe.blacklist=nouveau,nova_core,nova_drm"
PKG_KVER="7.2.0"

log() { printf '%s\n' "$*"; }
warn() { printf 'warning: %s\n' "$*" >&2; }
die() { printf 'error: %s\n' "$*" >&2; exit 1; }

# Resolve install prefix: "" means the live system.
ROOT="${SPK_ROOT:-/}"
PREFIX=""
case "$ROOT" in
    ""|"/") PREFIX="" ;;
    *) PREFIX="$(printf '%s' "$ROOT" | sed 's|/$||')" ;;
esac

MODPROBE_CONF="$PREFIX/etc/modprobe.d/nvidia.conf"
GRUB_DEFAULT="$PREFIX/etc/default/grub"
GRUB_CFG="$PREFIX/boot/grub/grub.cfg"

if [ "$(id -u)" -ne 0 ] && [ -z "$PREFIX" ]; then
    die "run as root: sudo nvidia-grub-setup"
fi

# 0) Overlay the payload into the system. spk isolates payloads under
# <root>/spk_pkgs/<pkg>, but kernel modules, firmware, Xorg/udev data and
# GL/Vulkan libs only work from their real locations - the loader, modprobe
# and Xorg never look inside the payload (this is why nvidia-smi used to
# fail with "couldn't find libnvidia-ml.so"). Copy - never move, spk still
# owns the payload - usr/ and etc/ over the target and record every
# installed path for `spk rm` in $SPK_APPDIR/system-files. For --root
# installs everything lands under $PREFIX instead of /.
if [ -n "${SPK_PKGDIR:-}" ] && [ -d "$SPK_PKGDIR/usr" ]; then
    LISTFILE=""
    if [ -n "${SPK_APPDIR:-}" ]; then
        mkdir -p "$SPK_APPDIR" 2>/dev/null || true
        LISTFILE="$SPK_APPDIR/system-files"
        : > "$LISTFILE" 2>/dev/null || LISTFILE=""
    fi
    for _sub in usr etc; do
        [ -d "$SPK_PKGDIR/$_sub" ] || continue
        mkdir -p "$PREFIX/$_sub" 2>/dev/null || die "cannot create $PREFIX/$_sub (run as root?)"
        if cp -a "$SPK_PKGDIR/$_sub/." "$PREFIX/$_sub/" 2>/dev/null; then
            log "installed $SPK_PKGDIR/$_sub -> $PREFIX/$_sub"
        else
            die "cannot copy $SPK_PKGDIR/$_sub to $PREFIX/$_sub (run as root?)"
        fi
        if [ -n "$LISTFILE" ]; then
            ( cd "$SPK_PKGDIR/$_sub" 2>/dev/null && find . -mindepth 1 \( -type f -o -type l \) | sed 's,^\./,,' | while IFS= read -r _rel; do
                printf '%s\n' "$PREFIX/$_sub/$_rel"
            done >> "$LISTFILE" ) 2>/dev/null || true
        fi
    done
    # one cache refresh for the overlaid libs (/usr/lib works without it
    # too, but only the cache covers every loader lookup)
    if command -v ldconfig >/dev/null 2>&1; then
        if [ -n "$PREFIX" ]; then
            ldconfig -r "$PREFIX" 2>/dev/null || warn "ldconfig -r $PREFIX failed; run ldconfig inside the target."
        else
            ldconfig 2>/dev/null || warn "ldconfig failed; run ldconfig by hand."
        fi
    else
        warn "ldconfig not found; newly installed libs may need a manual ldconfig."
    fi
fi

# The payload carries prebuilt modules for $PKG_KVER only - a different
# booted kernel will not load them, no matter what the rest of this script
# configures.
if [ -z "$PREFIX" ]; then
    _kver="$(uname -r 2>/dev/null || true)"
    if [ -n "$_kver" ] && [ "$_kver" != "$PKG_KVER" ]; then
        warn "running kernel $_kver != prebuilt modules $PKG_KVER; boot the $PKG_KVER kernel (spk linux package) or the driver will not load."
    fi
fi

# 1) modprobe blacklist + nvidia options (early-KMS safe, survives updates).
mkdir -p "$PREFIX/etc/modprobe.d"
cat > "$MODPROBE_CONF" <<'EOF'
# Generated by nvidia-grub-setup (spk nvidia / nvidia-legacy).
# Nouveau and the new NOVA (nova_core/nova_drm) drivers conflict with the
# proprietary NVIDIA driver. Blacklist them and load nvidia instead.
blacklist nouveau
blacklist nova_core
blacklist nova_drm
alias nouveau off
alias nova_core off
alias nova_drm off
options nvidia NVreg_PreserveVideoMemoryAllocations=1 NVreg_TemporaryFilePath=/var/tmp
options nvidia-drm modeset=1 fbdev=1
EOF
chmod 644 "$MODPROBE_CONF"
log "wrote $MODPROBE_CONF"
# removing the package must un-blacklist nouveau again - track this file for
# `spk rm` too (harmless if LISTFILE is unset, e.g. on manual re-runs)
if [ -n "${LISTFILE:-}" ]; then
    printf '%s\n' "$MODPROBE_CONF" >> "$LISTFILE" 2>/dev/null || true
fi

# 2) Patch grub defaults idempotently.
if [ ! -f "$GRUB_DEFAULT" ]; then
    warn "$GRUB_DEFAULT not found; skipping GRUB cmdline patch."
else
    # date is missing on truly minimal systems - fall back to the pid so a
    # missing date can never fail the install (the backup name just carries
    # no timestamp then).
    stamp="$(date +%Y%m%d%H%M%S 2>/dev/null || printf 'no-date-%s' "$$")"
    cp -a "$GRUB_DEFAULT" "$GRUB_DEFAULT.bak.$stamp"
    # Ensure the key exists.
    if ! grep -q '^GRUB_CMDLINE_LINUX_DEFAULT=' "$GRUB_DEFAULT"; then
        printf 'GRUB_CMDLINE_LINUX_DEFAULT="%s"\n' "$WANT_PARAMS" >> "$GRUB_DEFAULT"
        log "added GRUB_CMDLINE_LINUX_DEFAULT to $GRUB_DEFAULT"
    else
        # Append each wanted param only if missing. Operate on a temp copy.
        # mktemp is missing on truly minimal systems - without this fallback
        # the script used to die here with 127 (command not found) AFTER the
        # grub file was already patched. A pid-named file is good enough.
        tmp="$(mktemp 2>/dev/null || printf '%s/nvidia-grub-setup.%s.tmp' "${TMPDIR:-/tmp}" "$$")"
        [ -n "$tmp" ] || die "cannot create temp file (mktemp missing and TMPDIR unwritable)"
        cp "$GRUB_DEFAULT" "$tmp"
        # Extract current value of GRUB_CMDLINE_LINUX_DEFAULT (without quotes).
        current="$(sed -n 's/^GRUB_CMDLINE_LINUX_DEFAULT="\?\([^"]*\)"\?/\1/p' "$tmp" | head -n 1)"
        updated="$current"
        for p in $WANT_PARAMS; do
            case " $updated " in
                *" $p "*) ;;
                *) updated="$updated $p" ;;
            esac
        done
        # Trim leading space.
        updated="$(printf '%s' "$updated" | sed 's/^ *//')"
        # Escape for sed replacement.
        esc_updated="$(printf '%s' "$updated" | sed 's/[&/\]/\\&/g')"
        sed -i 's/^GRUB_CMDLINE_LINUX_DEFAULT=.*/GRUB_CMDLINE_LINUX_DEFAULT="'"$esc_updated"'"/' "$tmp"
        if cmp -s "$tmp" "$GRUB_DEFAULT"; then
            log "$GRUB_DEFAULT already contains NVIDIA params; no change."
        else
            cp "$tmp" "$GRUB_DEFAULT"
            log "patched $GRUB_DEFAULT:"
            grep '^GRUB_CMDLINE_LINUX_DEFAULT=' "$GRUB_DEFAULT" || true
        fi
        rm -f "$tmp"
    fi
    # Show effective cmdline for verification.
    log "effective: $(grep '^GRUB_CMDLINE_LINUX_DEFAULT=' "$GRUB_DEFAULT" || echo '(missing)')"
fi

# 3) depmod so the prebuilt 7.2.0 modules (and DKMS rebuilds) resolve.
if command -v depmod >/dev/null 2>&1; then
    if [ -n "$PREFIX" ]; then
        if [ -d "$PREFIX/lib/modules/$PKG_KVER" ]; then
            depmod -b "$PREFIX" -a "$PKG_KVER" 2>/dev/null || depmod -b "$PREFIX" "$PKG_KVER" 2>/dev/null || warn "depmod -b $PREFIX for $PKG_KVER failed"
            log "ran depmod -b $PREFIX for $PKG_KVER"
        else
            log "no $PREFIX/lib/modules/$PKG_KVER; skipping depmod for target"
        fi
    else
        if [ -d "/lib/modules/$PKG_KVER" ]; then
            depmod -a "$PKG_KVER" 2>/dev/null || warn "depmod -a $PKG_KVER failed"
            log "ran depmod for $PKG_KVER"
        fi
        if [ -d "/lib/modules/$(uname -r)" ]; then
            depmod -a "$(uname -r)" 2>/dev/null || depmod -a || true
            log "ran depmod for $(uname -r)"
        else
            depmod -a || true
            log "ran depmod -a"
        fi
    fi
else
    warn "depmod not found; skipping."
fi

# Steps 4-5 touch the running bootloader/initramfs: only valid on the live
# system. For --root installs the files above are staged under $ROOT and the
# target's own boot must be configured from inside it.
if [ -n "$PREFIX" ]; then
    log "installed into $PREFIX: GRUB config and modprobe staged, not activated."
    log "to activate inside that target, run: chroot $PREFIX nvidia-grub-setup"
    log "done. Then reboot that system and verify: cat /proc/cmdline should show nvidia-drm.modeset=1 and modprobe.blacklist; lsmod should show nvidia, not nouveau."
    exit 0
fi

# 4) Regenerate GRUB config. Best effort only: a present-but-broken
# grub-mkconfig (e.g. missing helpers in a minimal grub bundle) used to kill
# the whole install with its own exit code (127 when a helper is not found),
# even though the modprobe/grub-default changes above are the important part.
if command -v grub-mkconfig >/dev/null 2>&1; then
    mkdir -p "$(dirname "$GRUB_CFG")"
    if grub-mkconfig -o "$GRUB_CFG"; then
        log "regenerated $GRUB_CFG via grub-mkconfig"
    else
        rc=$?
        warn "grub-mkconfig failed (exit $rc); GRUB menu NOT regenerated - fix grub, then rerun: grub-mkconfig -o $GRUB_CFG"
    fi
elif command -v update-grub >/dev/null 2>&1; then
    if update-grub; then
        log "regenerated GRUB via update-grub"
    else
        rc=$?
        warn "update-grub failed (exit $rc); GRUB menu NOT regenerated - rerun update-grub by hand."
    fi
else
    warn "neither grub-mkconfig nor update-grub found; reinstall grub package and rerun."
fi

# 5) Rebuild initramfs so nouveau stays out of early boot.
rebuilt=""
if command -v mkinitcpio >/dev/null 2>&1; then
    mkinitcpio -P && rebuilt="mkinitcpio -P"
elif command -v dracut >/dev/null 2>&1; then
    dracut --force --regenerate-all && rebuilt="dracut"
elif command -v update-initramfs >/dev/null 2>&1; then
    update-initramfs -u && rebuilt="update-initramfs -u"
elif command -v booster >/dev/null 2>&1; then
    warn "booster detected; regenerate your initramfs images manually."
fi
if [ -n "$rebuilt" ]; then
    log "rebuilt initramfs via $rebuilt"
else
    warn "no initramfs tool (mkinitcpio/dracut/update-initramfs) found; if you use an initramfs, rebuild it manually so the blacklist applies early."
fi

log "done. Verify: cat /proc/cmdline should show nvidia-drm.modeset=1 and modprobe.blacklist; lsmod should show nvidia, not nouveau. Then reboot."
